export const users = [
    {
        first_name: "admin",
        last_name: "admin",
        address: "quezon",
        postcode: "1159",
        contact_phone_number: "639123456789",
        email: "admin@webapi.com",
        role: "admin",
        username: "admin",
        password: "password",
    },
    {
        first_name: "mikki",
        last_name: "jill",
        address: "quezon",
        postcode: "1159",
        contact_phone_number: "639123456789",
        email: "mikkijill@webapi.com",
        role: "user",
        username: "mikkijillmcsd",
        password: "password",
    },
    {
        first_name: "jay",
        last_name: "contreras",
        address: "cavite",
        postcode: "4100",
        contact_phone_number: "639123456789",
        email: "jaycontreras@webapi.com",
        role: "user",
        username: "jaycontr3ras",
        password: "password",
    },
    {
        first_name: "jayson",
        last_name: "astete",
        address: "la trinidad",
        postcode: "2601",
        contact_phone_number: "639123456789",
        email: "jaysonastete@webapi.com",
        role: "user",
        username: "mrputs",
        password: "password",
    },
    {
        first_name: "jomal",
        last_name: "linao",
        address: "quezon",
        postcode: "1116",
        contact_phone_number: "639123456789",
        email: "jomallinao@webapi.com",
        role: "user",
        username: "litolapis",
        password: "password",
    },
    {
        first_name: "led zeppelin",
        last_name: "tuyay",
        address: "quezon",
        postcode: "1116",
        contact_phone_number: "639123456789",
        email: "ledtuyay@webapi.com",
        role: "user",
        username: "led2eye",
        password: "password",
    },
    {
        first_name: "allan",
        last_name: "burdeos",
        address: "quezon",
        postcode: "1116",
        contact_phone_number: "639123456789",
        email: "allanburdeos@webapi.com",
        role: "user",
        username: "papibordskmkz",
        password: "password",
    },
    {
        first_name: "jianelli",
        last_name: "lubiano",
        address: "quezon",
        postcode: "1116",
        contact_phone_number: "639123456789",
        email: "jianlubiano@webapi.com",
        role: "user",
        username: "jianlubiano",
        password: "password",
    },
];
